services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: gunicorn composeexample.wsgi:application --bind 0.0.0.0:8090
    #command: python manage.py runserver 0.0.0.0:8090
    volumes:
      - .:/code
    ports:
      - "8090:8090"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build: vue
    volumes:
      - frontend_volume:/app
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  frontend_volume:
